name: user-signoff
run-name: Allows a user to sign off a PR check with a comment
on:
  issue_comment:
    types: [created, deleted]
  # pull_request:
  #   types: [opened, synchronize]
jobs:
  #list_props:
  #  runs-on: ubuntu-latest
  #  name: List props of github object
  #  if: ${{ github.event_name == 'pull_request' }}
  #  steps:
  #    - uses: actions/github-script@v6
  #      with:
  #        script: |
  #          const ghChecks = await github.rest.checks;
  #          console.log(ghChecks);
  #create_check:
  #  runs-on: ubuntu-latest
  #  if: ${{ github.event_name == 'pull_request' }}
  #  steps:
  #    - name: Create sign-off check
  #      id: create_check
  #      uses: actions/github-script@v6
  #      with:
  #        script: |
  #          const newCheck = await github.rest.checks.create({
  #            owner: context.repo.owner,
  #            repo: context.repo.repo,
  #            name: 'User Sign-Off Check',
  #            head_sha: context.payload.pull_request.head.sha,
  #            status: 'queued',
  #          });
  # list-checks:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: List checks on PR
  #       uses: actions/github-script@v6
  #       with:
  #         script: |
  #           const signoffCheck = await github.rest.repos.listCommitStatusesForRef({
  #             owner: context.repo.owner,
  #             repo: context.repo.repo,
  #             ref: context.payload.pull_request.head.sha,
  #             //check_name: 'User Sign-Off Check',
  #           });
  #           console.log('signoffCheck:');
  #           console.log(signoffCheck);
  #           //console.log('signoffCheck id: ' + signoffCheck.data.check_runs[0].id);
  #           //console.log('signoffCheck name: ' + signoffCheck.data.check_runs[0].name);
  user_signoff:
    runs-on: ubuntu-latest
    name: User signing off PR
    if: ${{ github.event_name == 'issue_comment' && github.event.issue.pull_request }}
    steps:
      - name: Sign off with the right user and message
        uses: actions/github-script@v6
        id: print-payload
        with:
          script: |
            console.log('Take 10');
            const signOffCheckName = 'User Sign-Off Check';
            const signOffCommentText = 'Ship it!';
            if (context.actor == 'khawkins' && context.payload.comment.body == signOffCommentText) {
              // We're going to need the SHA information from the PR.
              const issuePr = await github.rest.pulls.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number
              });
              const headSha = issuePr.data.head.sha;
              if (context.payload.action == "deleted") {
                console.log('Sign-off comment deleted. Re-requesting check run.');
                const checkRunsForPr = await github.rest.checks.listForRef({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  ref: headSha,
                  check_name: signOffCheckName,
                });
                if (checkRunsForPr.data.total_count > 0) {
                  console.log('Found ' + checkRunsForPr.data.total_count + ' check run(s) for "' + signOffCheckName + '".');
                  const signOffCheckRunId = checkRunsForPr.data.check_runs[0].id;
                  await github.rest.checks.update({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    check_run_id: signOffCheckRunId,
                    status: 'queued',
                  });
                } else {
                  console.log('No completed check runs found for "' + signOffCheckName + '". No action taken.');
                }
              } else if (context.payload.action == "created") {
                console.log('Got the right message from the right user!');
                const newCheck = await github.rest.checks.create({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  name: signOffCheckName,
                  head_sha: headSha,
                  status: 'completed',
                  conclusion: 'success',
                });
                console.log('Created sign-off check: ' + newCheck);
              } else {
                console.log('Unexpected value for issue_comment action: ' + context.payload.action);
              }
            } else {
              console.log('Either user (' + context.actor + ') or comment (' + context.payload.comment.body + ') is incorrect!');
            }
            return 0;
      - name: Get result
        run: echo "${{steps.print-payload.outputs.result}}"
