name: user-signoff
run-name: Accepts user comments on PRs
on: issue_comment
jobs:
  user-signoff:
    runs-on: ubuntu-latest
    name: User signing off PR
    if: ${{ github.event.issue.pull_request }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
      - run: |
          echo A comment on PR $NUMBER, redux2
        with:
          script: console.log(context)
